# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image1_tn', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image2_tn', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image3_tn', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image4_tn', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image5_tn', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image6_tn', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('image7_tn', models.ImageField(upload_to='images/')),
                ('image8', models.ImageField(upload_to='images/')),
                ('image8_tn', models.ImageField(upload_to='images/')),
                ('image9', models.ImageField(upload_to='images/')),
                ('image9_tn', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
