# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Soap',
        ),
    ]
