# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190322_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='soap',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
